### ISSUE TITLE
Discriminated unions throwing warnings

### ISSUE THREAD

**Issue by jettdc** [palantir/foundry-platform-python#54] opened 2024-10-22 14:48 UTC
```
StringType(type="string")
```
gives the following warning
```
  Failed to get discriminator value for tagged union serialization with value `{'type': 'string'}` - defaulting to left to right union serialization.
```

(as well as the rest of the union types)

**Comment by jettdc** [comment] 2024-10-22 14:48
My code has been running okay, but this may lead to incorrectness in some cases potentially if the unions are not serializing/deserializing correctly

**Comment by jsmith** [comment] 2024-11-28 18:03
Does running just `StringType(type="string")` cause that warning? I'm not able to reproduce but it could be a Pydantic version issue. If that's all it takes, could you provide the Pydantic and Python versions you're using?

**Comment by jsmith** [comment] 2024-11-28 19:34
Ok I've determined this is an issue with Pydantic `2.9.X` versions. This doesn't seem to be present in `2.8.X` versions or `2.10.X` versions (the latest minor version as of Nov 28th). Going to close this as a "won't fix" since newer versions of Pydantic don't present this warning.

**Closed as not planned by jsmith** 2024-11-28 19:34 UTC
